version: "3.8"

services:
  backend:
    build:
      context: ./nodejs-docker-web-app  # Corrected path to Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    restart: always  # Ensures Redis restarts if it fails